[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "readii-negative-controls"
platforms = ["linux-64"]
version = "0.1.0"


[system-requirements]
linux = "5.4.203"

[environments]
fmcib = { features = ["fmcib"], no-default-feature = true }

[tasks]
snake = "pixi run snakemake --use-conda -c all --keep-going"
dag = "snakemake -F --dag | dot -Tsvg > resources/dag.svg"
rulegraph = "snakemake -F --rulegraph | dot -Tsvg > resources/rulegraph.svg"
filegraph = "snakemake -F --filegraph | dot -Tsvg > resources/filegraph.svg"
graphs = { depends_on = [
  "dag",
  "rulegraph",
  "filegraph",
], description = "Generate all the graphs" }

[dependencies]
python = "==3.12"
ipython = "*"
jupyter = "*"
python-dotenv = ">=1.0.1,<2"
ruff = ">=0.8.4,<0.9"
mypy = ">=1.14.0,<2"
pydantic-settings = ">=2.7.0,<3"
snakemake = ">=8.26.0,<9"
pdbpp = ">=0.10.3,<0.11"

[activation.env]
IMGTOOLS_LOG_LEVEL = "INFO"
READII_LOG_LEVEL = "INFO"


[pypi-dependencies]
# med-imagetools = { git = "https://github.com/bhklab/med-imagetools.git", branch = "numpy2"}
# readii = { git = "https://github.com/bhklab/readii.git", rev = "affb9eac5e0c4130640079eb67d710b962a21f18" }
# nbia-toolkit = { git = "https://github.com/jjjermiah/nbia-toolkit.git", rev = "e8936a8dd9d20d494532c63e5d6ea9703149c0ad" }
med-imagetools = { path = "../repos/med-imagetools", editable = true }
readii = { path = "../repos/readii", editable = true }
nbia-toolkit = { path = "../repos/nbia-toolkit", editable = true }
readii_negative_controls = { path = ".", editable = true }

[feature.fmcib.dependencies]
python = "*"

[feature.fmcib.pypi-dependencies]
project-lighter = { version = "==0.0.2a19" }
foundation-cancer-image-biomarker = { version = "==1.0.0" }
