[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "readii-negative-controls"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
ipython = "*"
jupyter = "*"
python-dotenv = ">=1.0.1,<2"

[pypi-dependencies]
# med-imagetools = ">=1.10.1, <2"
med-imagetools = { git = "https://github.com/bhklab/med-imagetools.git", rev = "3463847307b50ca8acf1f3f139f26d9c751c3bac"}
# readii = ">=1.31.0, <2"
readii = { git = "https://github.com/bhklab/readii.git", rev = "affb9eac5e0c4130640079eb67d710b962a21f18"}
nbia-toolkit = { git = "https://github.com/jjjermiah/nbia-toolkit.git", rev = "e8936a8dd9d20d494532c63e5d6ea9703149c0ad"}
readii_negative_controls = { path = ".", editable = true }

[system-requirements]
linux = "5.4.203"